### ISSUE TITLE
GROUP_ID and USER_ID are empty or wrong in some cases

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/drupal-react-boilerplate#2]
I added as args at the `docker-compose.yml` file:
```yml
...
  app:
    extends: meta
    image: fiesc-vs-app
    build:
      context: ./docker/
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
...
```

For the MacOSX we need to export the env vars which were missing, adding these lines above at the Makefile:
```
# Configure environment.
# ----------------------

export TZ=America/Sao_Paulo
export USER_ID=$(shell id -u)

# @TODO Hack for MacOSX or other OS which has the same group id
#       than the containers user.
export GROUP_ID=$(shell if [ `id -g` == '20' ]; then echo '1000'; else echo `id -g`; fi)
```
