### ISSUE TITLE
Remove default libraries from SPA theme

### ISSUE THREAD

**Issue by sebas5384** [TallerWebSolutions/drupal-react-boilerplate#3]
It's really rare to need `jquery` and other tools from Drupal javascripts.

Here's a snippet of how we removed them in previous project.
Add to at the bottom of the info.yaml file of the React custom theme:
```yaml
libraries-override:
  core/drupal: false
  core/jquery: false
  core/drupal.active-link: false
  system/base: false
```

Could we add this as default?
